<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AssemblyTitle>PlistSerializer.Core.Tests</AssemblyTitle>
        <Product>PlistSerializer.Core.Tests</Product>
        <Copyright>Copyright ©  2019</Copyright>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>
        <FileVersion>1.0.0.0</FileVersion>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <ImplicitUsings>enable</ImplicitUsings>

        <!-- Enable Microsoft Testing Platform support for xUnit -->
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\PlistSerializer.Core\PlistSerializer.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="xunit.v3" Version="3.2.1" />
    </ItemGroup>
    <ItemGroup>
        <None Update="Resources\*.plist" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>
</Project>